import React from 'react'
import Link from 'next/link'

export const metadata = {
  title: 'Coc Can - Log In',
  description: 'Generated by create next app',
}

function LoginPage() {
  return (
    <>
        <div>Login</div>
    </>
    
  )
}

export default LoginPage