import React from 'react'

export const metadata = {
    title: 'Coc Can - Staff Log In',
    description: 'Generated by create next app',
  }

function StaffLogin() {
  return (
    <div>StaffLogin</div>
  )
}

export default StaffLogin